import test from 'node:test';
import assert from 'node:assert/strict';
import {editorialItems} from '../src/family-editorial.js';
const row = () => ({id:'seiche:example',title:'Funding source record',summary:'A public observation with limits.',date_published:'2026-09-20T10:00:00Z',url:'https://myquantdoesntspeakenglish.com/interpreted/example',external_url:'https://seiche.info/dispatches/example/',_mqdnse:{schema:'mqdnse.web-feed-item.v1',product:'seiche',lane:'INTERPRETED',sourceRecordId:'seiche:example',sourceUrl:'https://seiche.info/dispatches/example/',evidence:{publicationStatus:'PUBLISHED',limitation:'Funding context is not an institution score.'},copy:{inEnglish:'A public observation with limits.'}}});
const feed = rows => ({version:'https://jsonfeed.org/version/1.1',_mqdnse:{schema:'mqdnse.web-feed.v1',authority:'PUBLIC_EDITORIAL_ARCHIVE'},items:rows});
test('public editions retain publication date, original source and complete limits',()=>{const r=row();assert.deepEqual(editorialItems(feed([r])),[{id:r.id,product:'seiche',title:r.title,summary:r.summary,date:r.date_published,url:r.url,original:r.external_url,limitation:r._mqdnse.evidence.limitation,lane:'INTERPRETED'}]);});
test('suspended or mismatched channels cannot become published editorial previews',()=>{const wrong=feed([row()]);wrong._mqdnse.authority='SUSPENDED_SEPARATE_CHANNEL';assert.throws(()=>editorialItems(wrong));for(const mutate of [r=>r._mqdnse.evidence.publicationStatus='DRAFT',r=>r._mqdnse.sourceRecordId='another-record',r=>r.summary='Unbound promotional copy',r=>r._mqdnse.evidence.limitation='',r=>r.date_published='not a date']){const r=row();mutate(r);assert.deepEqual(editorialItems(feed([r])),[]);}});
test('unsafe links are refused and duplicated records do not crowd the preview',()=>{for(const url of ['javascript:alert(1)','https://attacker.invalid/story','https://secret@seiche.info/record']){const r=row();r.external_url=url;r._mqdnse.sourceUrl=url;assert.deepEqual(editorialItems(feed([r])),[]);}assert.equal(editorialItems(feed([row(),row()])).length,1);});

test('preview keeps the newest edition of a repeated desk headline',()=>{const older=row();const newer=row();newer.id='seiche:newer';newer._mqdnse.sourceRecordId=newer.id;newer.date_published='2026-09-23T10:00:00Z';assert.deepEqual(editorialItems(feed([older,newer])).map(item=>item.id),['seiche:newer']);});
